# get api_id & api_hash from my.telegram.org
api_id: 25455215
api_hash: '4008aeda4613fe9efe1dd8054803a1e5'
# 13 digit channel id startswith - like -111.......
dump_id: -1001841775749
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOMQBuzKnkRhwY-qtY9zWzqo1AlrQ5FbhqW9gcqsosfVxkWSxh4yvgWG4i1sikknTNnV3Bw0TitGBPj6fxiW1UziXSkuu3uzwJ2vGU4RxZpTPg1qOBuCbRQRCc3NSLnOef48beMSB8ZyhbuPLQuV6s1lbCMMNb4laiTUzEYN5Up4fgkGuYdhZYtDYzeqw83BFXSBe2vtvfyeFdbISpYiTXELe7KpAp2fUcVRWphJ1gLSk9iOMbq3ZDbMSYixS7bamax9QJ3-znuqd-hdir911xPDHcaNKB8gD8sA1eVeOd253_B2ZaTN1jyX5klunLw4edIz9PqOjOGiSgguIv_k5tKo9o54='
