# get api_id & api_hash from my.telegram.org
api_id: 25455215
api_hash: '4008aeda4613fe9efe1dd8054803a1e5'
# 13 digit channel id startswith - like -111.......
dump_id: -1001841775749
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOL8Bu1p-Gqi0gZ9ffMKZ7Co-MW9Epznp2kmMdW0EFjbcCf-3_uIib_H0-WuwEFX5TXl6JOhd7bh0X2R-zQr3QxnRAFThUQ8BvAYDG__frBKV_zhLiP8f87rfQHs4OHJGJ-dFjqTmon9sgSsncW3KrJZwZtXi-eDKraoK5d2I5fQh0umk585yH0sTnpthiSKeb_kjNRecHLY3a5RtboCkB9C6-7Ydm-Syb93Hp7X_25a7ySeubSjFkizTgKxtgBTY-K8NCiRDKPvqhFP5o4tf_MbERRLTO3oSqD6jjC7vWqZYNFfR9Z6rGOg-qi_-Qr3AHyPgSPkCKdc6bJj9LS1qKwgRy2M='
