# get api_id & api_hash from my.telegram.org
api_id: 27264334
api_hash: '0d48bec55aca309215ad69cb844868e5'
# 13 digit channel id startswith - like -111.......
dump_id: -1001753507640
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BJWap1sBu0_4IYIXRgMspsafZFOE5gnWtyDa5t52OfkEWMS5mtr-7KEYi_Ph7AuRdls5kemg_isXMRBme9gUDgnu232HzmMYBntf3_BSo1rQuQTtsEpCqaIYSMhcKSoChqXsheSgS78GZ9fd6QeHS4U4HKJVeX9Ald6aR6y32JPqd8aHlyiRGbPq4WbEnj0Md3g5ussrHNej4_6mxBb4eHv-sFrTQeZafTaiyzva-zFfU-LtErthMUmBztIYlAT2PCkYAYr6CGiD5Nn6ne1jt6opF-6B67Ukh-V6WwrBVUymGpdpVN020ojs2aoprO9Vu8Xt11vrFVIymJd65QtuySZV_7cMyYg='
