# get api_id & api_hash from my.telegram.org
api_id: 27264334
api_hash: '0d48bec55aca309215ad69cb844868e5'
# 13 digit channel id startswith - like -111.......
dump_id: -1001841775749
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BJWap1wBuyIhbn7sZABI5tvL1FbE6i-fhwQu8tp5pEZlDFiS358qN6qN8CZ_tGNpzQjkYwzChmMu-yuRkL-1E1vG9ghGk_7Ofo3lS_GU9tmXmZZGbdl58aPsQmCYis4MkK7ddwRR7S-zJ-__lJ2bb9ohyUduYl00zUIvikvJjPX1NVaLF3JfQuqu8jXdLkXKweTikfoTl7gMtNMNreqYQuLz7s8mTW1XAu99U-AU_Wtes9TFwBeiTCZyD3gVdtRKEonHveAUeDx4vHIWbz5npkmh1CjcNPGLCCuJRE1QvLqf7ELDOqCG_bjEoJo_ou8i2QNOkW1pX1mXM1rMRFkuHtwHTwxz9ss='
